### ISSUE TITLE
Bug: Unable to delete ~/.qlty without sudo

### ISSUE THREAD

**Issue by joshknowles** [qltysh/qlty#1159]
### What happened?

`rm -Rf ~/.qlty` fails as some files in the `cache` folder do not have write permission which is preventing the `~/.qlty` from being able to be deleted

![image](https://github.com/user-attachments/assets/e32a0aa9-35b2-4685-b5e9-3acbaa9e3804)

### What did you expect to happen?

Ability to delete ~/.qlty as the user that installed it

### Can you reproduce the problem?

Yes, consistently

### CLI Version

too late, deleted half the files

**Comment by marschattha** [comment]
Confirmed this issue.

It seems 2 plugins gofmt and shfmt, both of which are installed by go exhibit this behaviour the directories don't have write permission for the user(dr-xr-xr-x) making them unable to be removed without root/sudo.

These directories are not touched after the initial tool install probably at which point they have said permissions.
Don't think we can alter them since qlty doesn't run as root/sudo.

**Comment by brynary** [comment]
Since this is a behavior in the way Go downloads dependencies, and there's not a clear change we could make to improve this (without risking other issues), we are going to close this as a wontfix.
